import { Box, Image, SimpleGrid } from "@chakra-ui/react";
import React from "react";

const NewlyCollections = () => {
  return (
    <>
      <SimpleGrid
        pt={"50px"}
        pb={"50px"}
        w={"100%"}
        display={"grid"}
        gap={"10px"}
        m={"auto"}
        columns={[1, 2, 3, 4]}
      >
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={"https://i.ytimg.com/vi/-ZKzfLTTdU8/maxresdefault.jpg"}
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://diyjoy.com/wp-content/uploads/2020/01/paper-rose-mobile-1.jpg"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://popitout.in/cdn/shop/products/1_6_9a1ff9a0-5684-4293-831c-9ff85ce6e059.jpg?v=1639656601"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://cdn.igp.com/f_auto,q_auto,t_pnopt9prodlp/products/p-shower-your-loved-ones-with-this-bouquet-of-30-red-roses-6632-m.jpg"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize={"200px"}
            objectFit={"cover"}
            mx="auto"
            w={"100%"}
            src={
              "https://gingercup.com/blog/wp-content/uploads/2018/04/coffee-cup-art.jpg"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://images.shaadisaga.com/shaadisaga_production/photos/pictures/001/832/128/new_medium/8.jpg?1594396175"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://www.deliciaecakes.com/static/1b81efd72d392bb1486fd93a82523da7/0f3a1/3d-2360.jpg"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://5.imimg.com/data5/SELLER/Default/2023/2/AA/GC/MN/87263187/metal-wall-art-500x500.jpg"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://cdn.shopify.com/s/files/1/0047/4231/6066/files/6_fe62830b-0b13-47df-9373-9f5020fb93a7_480x480.jpg"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://i.etsystatic.com/14205793/r/il/17e27d/3464738411/il_fullxfull.3464738411_ktvl.jpg"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://diyjoy.com/wp-content/uploads/2021/04/paint-wine-bottle-1.jpg"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://content.jdmagicbox.com/comp/delhi/w3/011pxx11.xx11.191213121157.r8w3/catalogue/dev-mehandi-art-dwarka-sector-12-delhi-bridal-mehendi-artists-d1us1efrxb.jpg?clr="
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://i.pinimg.com/736x/75/e8/23/75e823578e82d1e6496fe8c67c8ac9d2.jpg"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={
              "https://sites.create-cdn.net/siteimages/54/9/4/549435/20/0/3/20031292/1000x855.jpeg?1655813228"
            }
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={"https://i.ytimg.com/vi/PSEAbeE83xg/maxresdefault.jpg"}
            alt="img"
          />
        </Box>
        <Box>
          <Image
            boxSize="200px"
            objectFit="cover"
            mx="auto"
            w={"100%"}
            src={"https://i.ytimg.com/vi/LE3igXSO4OI/maxresdefault.jpg"}
            alt="img"
          />
        </Box>
      </SimpleGrid>
    </>
  );
};

export default NewlyCollections;
